= 2.26.1102
:imagesdir: img

== Description
EtherCAT: Distributed Clocks sync lost

== Cause

The sync deviation in at least one slave is higher than the allowed value across several clocks. Possibly the slave has not received a DC packet with the reference time. This can occur due to a loose cable contact, cable break or similar. The error message normally does not appear alone but in conjunction with other error messages such as 2.26.511 EtherCAT: Statepolling: No response from slave. Check wiring and reload machineconstants/PLC, 2.26.401 EtherCAT: Slave reported errorstate, 2.26.401 EtherCAT: Unexpected slave state detected.Possible solutionCheck wiring und restart EtherCAT:? Do the RJ45 connectors sit firmly in the EtherCAT socket of the slaves?? Are the latches properly engaged or broken off?? Reload machine constants or reload PLC for systems without axes? At which position in the topology such a problem may occur can be limited by reading out the error counters in the EtherCAT devices (monitor command ecat errcnt).

== Action
 
 

== Effect
 

