= 2.3.1210
:imagesdir: img

== Description
WOK: G41/G4 C-axis should be traced and is not configured

== Cause
When switching on the tool radius compensation with G41/G42, it was specified in parameter E that the C axis should be traced tangentially. However, no C axis is configured in the machine constants and no transformation is active to create a "virtual" C axis.

== Action

 Check the machine constants and the call sequence of transformations and tool compensation in DIN program/cycles.Further documentationG41 Cutter compensation - left (see also CNC Programming Manual in EEDP) G42 Cutter compensation - right (see also CNC Programming Manual in EEDP)If the error occurs with the ECUT application package:In bevel cutting, there are kinematics with A and B axis. The C axis is not configured in the machine constants. G114 6-axis transformation (RTCP) (see also CNC Programming Manual in EEDP)In the DIN program a G41 R=P1500 E1 is written. Here, "E1 = tangential tracking on". The C axis is to be tracked in this case. If the message appears directly after START, the corresponding head on the machine panel (S8) may not be selected.

== Effect
 

